### ISSUE TITLE
Feedback on initial work

### ISSUE THREAD

**Issue by ysb33r** [gradle-guides/guides-test-fixtures#1]
*Positives*:

- The concepts captured in the `FunctionalTestFixture` interface is great. Ir covers a numbe of things that is required.
- Also the idea behind `AbstractSamplesFunctionalTest` is good.

*Negatives*:

- The assumption currently is that there is one sample project and it will be copied as-is from every test case. This is not necessarily true. In cases like Getting Started guides, working through steps means that one or more sample project may exist. Or that parts of files are modified as the the tests progress. For instance in the `building-java-web-applications` guide the `build.gradle` file has three incantantions. There one base project was used and two additional `build.gradle` files that were copied over the original. What I am saying is that one should be straing oneself blind against the one-project-is-good-enough test-case.
- Output testing comes in a number of forms and I have not seen anything yet that helps with that. Typical cases are:
  - Does the output contain the following text?
  - Should any text be removed from the output before comparing?

*Other:*
- Use of `@Unroll` in Spock makes a big difference in testing a variety of cases of saying *Do X with Gradle Build Tool*, *check the output against this file*. To a great extent this can gover the functionality of `gradleRunner`.
- How are we goign to deal with the Gradle 4.0 output going forward?

**Comment by bmuschko** [comment]
> The assumption currently is that there is one sample project and it will be copied as-is from every test case.

The code doesn't necessarily force you into that. There's a method for copying a sample directory but that doesn't mean that you cannot add more files, modify them or remove them if needed.

> For instance in the building-java-web-applications guide the build.gradle file has three incantantions. There one base project was used and two additional build.gradle files that were copied over the original.

I'd personally set up 3 different sample projects for this use case. Each of the projects would be testable by itself. Yes, there would be some duplication but users can directory navigate to a sample project and try out a specific, self-contained step. I think that it is actually very beneficial to users to be able to try out a step as-is without having to manually make changes (that they do get wrong sometimes).

> Output testing comes in a number of forms and I have not seen anything yet that helps with that. 

So far I didn't think that there's much benefit of implementing a convenience method. I'd usually just say `buildResult.output.contains(<the-string-i-want-assert>)`. I could imagine having a method `containsOutput(<the-string-i-want-assert>)` but I am not sure if it would be of much help. Often times there's something else you will want to assert from the build result so you have to get a handle to it anyway.

> How are we goign to deal with the Gradle 4.0 output going forward?

What I have done so far is to just check in the expected output (as a user would see it meaning `--console=rich`) under `samples/outputs` and reference it in the Asciidoc file. At the moment I do not test the output as you can't get rich console output from an execution of the tooling API. I was asking about it internally but haven't gotten an answer yet. Will keep you in the loop.

Question: Do you think this is useable overall?

**Comment by ysb33r** [comment]
> So far I didn't think that there's much benefit of implementing a convenience method. I'd usually just say buildResult.output.contains(<the-string-i-want-to-assert>). I could imagine having a method containsOutput(<the-string-i-want-to-assert>) but I am not sure if it would be of much help. Often times there's something else you will want to assert from the build result so you have to get a handle to it anyway.

I think this is where we have to leave it for now. For it to be really cool it will need to be a Spock Extension - it might be too much work for too little gain.

> Question: Do you think this is useable overall?

Yes. If you can work that into the plugin, so that it ends up on the classpath for testing, then it woul dbe good.
