### ISSUE TITLE
Cn we have Iterable<String> equivalents

### ISSUE THREAD

**Issue by ysb33r** [gradle-guides/guides-test-fixtures#2]
For methods such as https://github.com/gradle-guides/guides-test-fixtures/blob/master/src/main/java/org/gradle/guides/test/fixtures/DefaultFunctionalTestFixture.java#L49, can be have equivalent methods that take `Iterable<String> as parameter? This removes the need to add ugly `toArray` conversions in the test code.

**Comment by bmuschko** [comment]
https://github.com/gradle-guides/guides-test-fixtures/pull/3

**Comment by bmuschko** [comment]
Available with version 0.2.
