### ISSUE TITLE
Add support for running all samples in a directory

### ISSUE THREAD

**Issue by wolfs** [gradle-guides/guides-test-fixtures#6]
Like I did for the build cache guide here: https://github.com/gradle-guides/using-build-cache/blob/4af8920e27e4e249ed32d7af62dfe68814104c00/src/test/groovy/org/gradle/guides/caching/SamplesIntegrationTest.groovy#L16-L30

**Comment by wolfs** [comment]
This should probably be a Spock extension.

**Comment by lacasseio** [comment]
We will most likely address this differently as part of the improved testing for samples and guides.
